const dresses=[
 {id:'dress-1',name:'Платье 01',price:12000,color:'Айвори',sizes:['XS','S','M'],image:'assets/dress-01.png?v=3',desc:'Атласное платье с высоким разрезом и струящимся шлейфом.'},
 {id:'dress-2',name:'Платье 02',price:8000,color:'Айвори',sizes:['XS','S'],image:'assets/dress-02.png?v=3',desc:'Короткое платье с объёмной юбкой и кружевными деталями.'},
 {id:'dress-3',name:'Платье 03',price:16000,color:'Айвори',sizes:['S','M','L'],image:'assets/dress-03.png?v=3',desc:'Кружевное платье-русалка с длинным шлейфом.'},
 {id:'dress-4',name:'Платье 04',price:18000,color:'Айвори',sizes:['S','M'],image:'assets/dress-04.png?v=3',desc:'Сияющее платье-футляр с длинной фатой.'},
 {id:'dress-5',name:'Платье 05',price:14000,color:'Айвори',sizes:['S','M','L','XL'],image:'assets/dress-05.png?v=3',desc:'Пышное платье с корсетом и выразительными рукавами.'},
 {id:'dress-6',name:'Платье 06',price:17000,color:'Айвори',sizes:['XS','S','M'],image:'assets/dress-06.png?v=3',desc:'Сверкающее платье-русалка на тонких бретелях.'}];
let state={cart:JSON.parse(localStorage.getItem('kovik-cart')||'[]')};
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽',byId=id=>dresses.find(x=>x.id===id),$=s=>document.querySelector(s);
function bounds(){let min=+$('#minPrice').value,max=+$('#maxPrice').value;if(min>max){[min,max]=[max,min];if(document.activeElement===$('#minPrice'))$('#maxPrice').value=max;else $('#minPrice').value=min}$('#minPriceLabel').value=money(min);$('#maxPriceLabel').value=money(max);return[min,max]}
function filtered(){let[min,max]=bounds(),c=$('#color').value,s=$('#size').value;return dresses.filter(x=>x.price>=min&&x.price<=max&&(c==='all'||x.color===c)&&(s==='all'||x.sizes.includes(s)))}
function renderProducts(){let r=filtered();$('#products').innerHTML=r.length?r.map(d=>`<article class="product-card" data-id="${d.id}"><div class="product-photo"><img src="${d.image}" alt="${d.name}"></div><p>${money(d.price)} / 4 дня</p></article>`).join(''):'<p class="empty">По этим фильтрам платьев пока нет.</p>'}
function updateCount(){let n=state.cart.length;$('#cartCount').textContent=$('#detailCart').textContent=n;localStorage.setItem('kovik-cart',JSON.stringify(state.cart))}
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function openDetail(id){let d=byId(id);$('#detailBody').innerHTML=`<img class="detail-img" src="${d.image}" alt="${d.name}"><section class="detail-copy"><div class="detail-title"><h1>${d.name}</h1><strong>${money(d.price)}<small>/ 4 дня</small></strong></div><p>${d.desc}</p><h3>Размер</h3><div class="sizes">${d.sizes.map(x=>`<button>${x}</button>`).join('')}</div><button class="detail-add" data-add="${d.id}">Добавить в корзину&nbsp; →</button><div class="benefits"><div><b>▣</b>Самовывоз</div><div><b>♧</b>Чистка включена</div><div><b>◇</b>Бережный сервис</div></div></section>`;$('#detail').classList.add('open')}
function renderCart(){let a=state.cart.map(byId);$('#cartItems').innerHTML=a.length?a.map(d=>`<div class="cart-row"><img src="${d.image}" alt="${d.name}"><div><h3>${d.name}</h3><p>4 дня</p><strong>${money(d.price)}</strong></div><button class="remove" data-remove="${d.id}">×</button></div>`).join(''):'<div class="empty">Ваша корзина пока пуста.</div>';$('#cartTotal').textContent=money(a.reduce((s,x)=>s+x.price,0))}
function openCart(){renderCart();$('#cart').classList.add('open')}
function closeFilters(){ $('#filters').classList.remove('open'); $('#filterBackdrop').classList.remove('open'); $('#filters').setAttribute('aria-hidden','true'); $('.filter-toggle').setAttribute('aria-expanded','false') }
function openFilters(){ $('#filters').classList.add('open'); $('#filterBackdrop').classList.add('open'); $('#filters').setAttribute('aria-hidden','false'); $('.filter-toggle').setAttribute('aria-expanded','true') }
document.addEventListener('click',e=>{let card=e.target.closest('.product-card');if(card)openDetail(card.dataset.id);let a=e.target.closest('[data-add]');if(a){if(!state.cart.includes(a.dataset.add))state.cart.push(a.dataset.add);updateCount();toast('Платье добавлено в корзину')}let rm=e.target.closest('[data-remove]');if(rm){state.cart=state.cart.filter(x=>x!==rm.dataset.remove);updateCount();renderCart()}if(e.target.closest('.cart-open')||e.target.closest('.bag'))openCart();if(e.target.closest('.close-cart'))$('#cart').classList.remove('open');if(e.target.closest('.back'))$('#detail').classList.remove('open');if(e.target.closest('.filter-toggle'))openFilters();if(e.target.closest('.filters-close')||e.target.closest('#filterBackdrop'))closeFilters();if(e.target.closest('#clearFilters')){$('#color').value=$('#size').value='all';$('#minPrice').value=8000;$('#maxPrice').value=18000;renderProducts()}if(e.target.closest('.checkout'))toast('Заявка станет доступна после подключения записи')});
[$('#minPrice'),$('#maxPrice'),$('#color'),$('#size')].forEach(x=>x.addEventListener('input',renderProducts));renderProducts();updateCount();
